package com.andydaykin.projecteuler;

/**
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 The first ten terms would be:
 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28

 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */
public class P12
{
    public static void main(String [] args)
    {
        boolean found = false;
        int i = 1;
        int triNum = 1;
        while(!found) {
            i++;
            triNum += i;

            int divisors = 0;
            for(int j = 1; j <= triNum / 2; j++) {
                if(triNum % j == 0) {
                    divisors++;
                }
            }
            //System.out.println(triNum + "--" + divisors);
            if(divisors > 500) {
                found = true;
            }
        }

        System.out.println("The first triangle number with > 500 divisors is: " + triNum);
    }
}

